# Generated by Django 3.2.8 on 2021-11-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='progress',
            field=models.CharField(blank=True, choices=[('seleccione', 'Seleccione'), ('15%', '15%'), ('30%', '30%'), ('45%', '45%'), ('60%', '60%'), ('75%', '75%'), ('90%', '90%'), ('100%', '100%')], default='seleccione', max_length=10),
        ),
    ]
