# Generated by Django 3.2.8 on 2021-11-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_skills_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
