# Generated by Django 3.2.8 on 2021-12-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_cvdowload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CvDowload',
            new_name='CvDownload',
        ),
    ]
