# Generated by Django 3.2.8 on 2022-02-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_certificates_company_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='date',
            field=models.DateField(),
        ),
    ]
