# Generated by Django 3.2.8 on 2022-02-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_certificates_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='progress',
        ),
        migrations.AddField(
            model_name='skills',
            name='icon_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
