# Generated by Django 3.2.8 on 2022-02-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20220220_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='picture_skills',
        ),
        migrations.AddField(
            model_name='skills',
            name='icon_img',
            field=models.ImageField(blank=True, null=True, upload_to='icon_img/'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='icon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
