# Generated by Django 3.2.8 on 2022-02-20 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20220220_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='icon_img',
            field=models.FileField(blank=True, null=True, upload_to='icon_img/', validators=[django.core.validators.FileExtensionValidator(['png', 'svg', 'jpg'])]),
        ),
    ]
