# Generated by Django 3.2.8 on 2022-02-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='data_language',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
