# Generated by Django 3.2.8 on 2022-02-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_rename_certificates_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='greeting_en',
            field=models.CharField(default=1, help_text='Greeting English', max_length=50),
            preserve_default=False,
        ),
    ]
