# Generated by Django 3.2.8 on 2022-02-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_home_greeting_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='name_en',
            field=models.CharField(default=1, help_text='Name-en', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='sub_greeting_en',
            field=models.CharField(default='', help_text='Sub-greeting-En', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='text_en',
            field=models.TextField(blank=True, help_text='Text-En', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='career_en',
            field=models.CharField(default=1, help_text='Career-En', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description-En'),
        ),
        migrations.AddField(
            model_name='profile',
            name='heading_en',
            field=models.CharField(default=1, help_text='Heading-En', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description-En', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(default=1, help_text='Title-En', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='greeting_en',
            field=models.CharField(help_text='Greeting-En', max_length=50),
        ),
    ]
