# Generated by Django 3.2.8 on 2022-02-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_auto_20220223_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
