# Generated by Django 3.2.8 on 2022-02-24 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_category_name_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
